#!/bin/bash

USERID=atulvarshneya
NEWVER=v3

echo "==LOGIN INTO DOCKER============================"
docker login --username=$USERID

for tag in py2 py3 gpu-py2 gpu-py3; do
	echo "Building ${tag} ======================================================"
	cat Dockerfile-Head-"${tag}" Dockerfile-CommonTail > Dockerfile
	docker build -q -t $USERID/ml-image:${NEWVER}-"${tag}" .
	# docker tag $USERID/ml-image:${NEWVER}-"${tag}" $USERID/ml-image:latest-"${tag}"
	docker push $USERID/ml-image:${NEWVER}-"${tag}"
	# docker push $USERID/ml-image:latest-"${tag}"
	rm Dockerfile
	echo "DONE building ${tag} ================================================="
done
