#!/bin/bash

USERID=atulvarshneya
NEWVER=
LATEST_TOO=

##
## Simple command line arguments parsing
##
USAGE=$(cat <<EOM
Usage: `basename $0` OPTIONS
Options:
-f       Tag latest also    Latest tag will be updated IF this flag is there
-t       Version tag        MANDATORY. The verson tag e.g., v3
EOM
)
while getopts ":hft:" arg; do
	case $arg in
		t)
			NEWVER="$OPTARG"
			;;
		f)
			LATEST_TOO="YES"
			;;
		h)
			echo "$USAGE"
			exit 0
			;;
		\?)
			echo "$USAGE"
			exit 1
			;;
	esac
done

if [ -z "$NEWVER" ] ; then
	echo "Version tag not provided. Cannot build without it."
	echo ""
	echo "$USAGE"
	exit 1
fi

echo "Building versions = $NEWVER"
if [ -z "$LATEST_TOO" ] ; then
	echo "NOT tagging them as the latest."
else
	echo "ALSO tagging them as the latest."
fi

echo "==LOGIN INTO DOCKER============================"
docker login --username=$USERID

for tag in py2 py3 gpu-py2 gpu-py3; do
	echo "Building ${tag} ======================================================"
	docker build -f Dockerfile-${tag} -t $USERID/ml-image:${NEWVER}-"${tag}" .
	docker push $USERID/ml-image:${NEWVER}-"${tag}"
	if [[ "$LATEST_TOO" =~ "YES" ]] ; then
		docker tag $USERID/ml-image:${NEWVER}-"${tag}" $USERID/ml-image:latest-"${tag}"
		docker push $USERID/ml-image:latest-"${tag}"
	fi
	echo "DONE building ${tag} ================================================="
done
