FROM atulvarshneya/ml-image:latest-py3
MAINTAINER "atul.varshneya@gmail.com"
RUN apt-get update
RUN apt-get install -y cmake
RUN pip install gym
RUN pip install gym[atari]
CMD ["/usr/local/bin/jupyter", "notebook", "--allow-root"]
