FROM tensorflow/tensorflow:latest-gpu-py3
# v1
MAINTAINER "atul.varshneya@gmail.com"
RUN rm BUILD LICENSE 1_hello_tensorflow.ipynb 2_getting_started.ipynb 3_mnist_from_scratch.ipynb
RUN pip install --upgrade pip
RUN pip install keras seaborn xlrd dill flask requests gunicorn xgboost
# CMD ["/usr/local/bin/jupyter" "notebook" "--allow-root"]
# v3
RUN apt-get update && apt install -y default-jdk
RUN pip install requests tabulate scikit-learn colorama future http://h2o-release.s3.amazonaws.com/h2o/rel-wolpert/8/Python/h2o-3.18.0.8-py2.py3-none-any.whl
# CMD ["/usr/local/bin/jupyter", "notebook", "--allow-root"]
# v4
RUN pip install imageio
# CMD ["/usr/local/bin/jupyter", "notebook", "--allow-root"]
# v5
RUN add-apt-repository -y ppa:marutter/rrutter
RUN apt-get update
RUN apt-get install -y r-base r-base-dev
RUN apt-get install -y libcurl4-gnutls-dev libssl-dev
RUN apt-get install -y r-cran-rjava
COPY install-irkernel-addlpkgs.R /tmp
RUN Rscript /tmp/install-irkernel-addlpkgs.R
RUN pip install tzlocal
RUN pip install rpy2
CMD ["/usr/local/bin/jupyter", "notebook", "--allow-root"]
